# Generated by Django 3.1.2 on 2020-10-31 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('service_type', models.CharField(choices=[('Hospital', 'Hospital'), ('Police', 'Police'), ('Fire', 'Fire')], max_length=60)),
                ('location', models.CharField(blank=True, max_length=60)),
                ('contact', models.CharField(blank=True, max_length=60)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hood.neighbourhood')),
            ],
        ),
    ]
